00003
Sephirot92/leggeart pull request #3
Opened 2021-01-10 22:22 UTC by Sephirot92

Added Service, Service Implementation class and basic Lawsuit class in version 0.0.1.

2021-01-11 14:19 UTC, ganzes requested changes

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/Lawsuit.java
> +@Entity
@Entity(name = "LAWSUITS")
you don't have to add adnotations @Table if you have already @Entity

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/Lawsuit.java
> +    private int id;
@Column(name="ID")

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/Lawsuit.java
> +    @Column (name = "THEME", nullable = false)
IMO motive should be better than theme

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/Lawsuit.java
> +        this.begginingDate = new Date();
this.begginingDate = new Date();
>        this.begginingDate = begginingDate;
you don't have to initiate object new Date() here imho, or you had to do exactly in this manner this.endingDate = endingDate;

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/LawsuitRepository.java
> + Dao class to handle Lawsuit class.
DAO is not a repository 
https://www.baeldung.com/java-dao-vs-repository#:~:text=DAO%20works%20as%20a%20data,be%20implemented%20using%20a%20repository.

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/LawsuitRepository.java
> +public interface LawsuitRepository extends JpaRepository<Lawsuit, Integer> {
public interface LawsuitRepository extends JpaRepository<Lawsuit, Integer> {
> public interface LawsuitRepository extends JpaRepository<Lawsuit, Long>

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/Lawsuit.java
> +    private int id;
i would make id as a long;

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/LawsuitService.java
> +public interface LawsuitService {
@Service
we are using Spring, annotations ad the top of every class is strongly recommended.

2021-01-11 14:19 UTC, ganzes commented on src/main/java/com/leggeart/legge/LawsuitServiceImpl.java
> +public class LawsuitServiceImpl implements  LawsuitService{
IMO you don't have to add another class, you could have all those methods in LawsuitService.
Also, you need to add annotations at the top - @Service

2021-01-12 09:18 UTC, Sephirot92 commented
Can you see those changes?

2021-01-12 09:32 UTC, ganzes approved these changes

2021-01-13 17:17 UTC, merged